export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const REGISTERACTIVATION_START = 'REGISTERACTIVATION_START';
export const REGISTERACTIVATION_SUCCESS = 'REGISTERACTIVATION_SUCCESS';
export const REGISTERACTIVATION_FAILED = 'REGISTERACTIVATION_FAILED';
export const REGISTERACTIVATION_CLEAR = 'REGISTERACTIVATION_CLEAR';

export const RESETPASSWORDEMAIL_START = 'RESETPASSWORDEMAIL_START';
export const RESETPASSWORDEMAIL_SUCCESS = 'RESETPASSWORDEMAIL_SUCCESS';
export const RESETPASSWORDEMAIL_FAILED = 'RRESETPASSWORDEMAIL_FAILED';
export const RESETPASSWORDEMAIL_CLEAR = 'RRESETPASSWORDEMAIL_CLEAR';

export const RESETPASSWORD_START = 'RESETPASSWORD_START';
export const RESETPASSWORD_SUCCESS = 'RESETPASSWORD_SUCCESS';
export const RESETPASSWORD_FAILED = 'RESETPASSWORD_FAILED';
export const RESETPASSWORD_CLEAR = 'RESETPASSWORD_CLEAR';

export const PROFILE_PICTURE_UPDATE_SUCCESS = 'PROFILE_PICTURE_UPDATE_SUCCESS';
export const PROFILE_PICTURE_UPDATE_FAILED = 'PROFILE_PICTURE_UPDATE_FAILED';
export const PROFILE_PICTURE_CLEAR_MESSAGES = 'PROFILE_PICTURE_CLEAR_MESSAGES';

export const PROFILE_PASSWORD_UPDATE_SUCCESS = 'PROFILE_PASSWORD_UPDATE_SUCCESS';
export const PROFILE_PASSWORD_UPDATE_FAILED = 'PROFILE_PASSWORD_UPDATE_FAILED';
export const PROFILE_PASSWORD_UPDATE_START = 'PROFILE_PASSWORD_UPDATE_START';

export const GET_ALL_USERS_START = 'GET_ALL_USERS_START'; 
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'; 
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED'; 

export const GET_SINGLE_USER_SUCCESS = 'GET_SINGLE_USER_SUCCESS'; 
export const GET_SINGLE_USER_FAILED = 'GET_SINGLE_USER_FAILED';
export const DELETE_SINGLE_USER_SUCCESS = 'DELETE_SINGLE_USER_SUCCESS';

export const GET_USER_ROLES_SUCCESS = 'GET_USER_ROLES_SUCCESS'; 
export const GET_USER_ROLES_FAILED = 'GET_USER_ROLES_FAILED'; 