export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const REGISTERACTIVATION_START = 'REGISTERACTIVATION_START';
export const REGISTERACTIVATION_SUCCESS = 'REGISTERACTIVATION_SUCCESS';
export const REGISTERACTIVATION_FAILED = 'REGISTERACTIVATION_FAILED';
export const REGISTERACTIVATION_CLEAR = 'REGISTERACTIVATION_CLEAR';

export const RESETPASSWORDEMAIL_START = 'RESETPASSWORDEMAIL_START';
export const RESETPASSWORDEMAIL_SUCCESS = 'RESETPASSWORDEMAIL_SUCCESS';
export const RESETPASSWORDEMAIL_FAILED = 'RRESETPASSWORDEMAIL_FAILED';
export const RESETPASSWORDEMAIL_CLEAR = 'RRESETPASSWORDEMAIL_CLEAR';

export const RESETPASSWORD_START = 'RESETPASSWORD_START';
export const RESETPASSWORD_SUCCESS = 'RESETPASSWORD_SUCCESS';
export const RESETPASSWORD_FAILED = 'RESETPASSWORD_FAILED';
export const RESETPASSWORD_CLEAR = 'RESETPASSWORD_CLEAR';

export const PROFILE_PICTURE_UPDATE_START = 'PROFILE_PICTURE_UPDATE_START';
export const PROFILE_PICTURE_UPDATE_SUCCESS = 'PROFILE_PICTURE_UPDATE_SUCCESS';
export const PROFILE_PICTURE_UPDATE_FAILED = 'PROFILE_PICTURE_UPDATE_FAILED';
export const PROFILE_PICTURE_CLEAR_MESSAGES = 'PROFILE_PICTURE_CLEAR_MESSAGES';

export const PROFILE_PASSWORD_UPDATE_SUCCESS = 'PROFILE_PASSWORD_UPDATE_SUCCESS';
export const PROFILE_PASSWORD_UPDATE_FAILED = 'PROFILE_PASSWORD_UPDATE_FAILED';
export const PROFILE_PASSWORD_UPDATE_START = 'PROFILE_PASSWORD_UPDATE_START';

export const GET_ALL_USERS_START = 'GET_ALL_USERS_START'; 
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'; 
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED'; 
export const GET_SINGLE_USER_SUCCESS = 'GET_SINGLE_USER_SUCCESS'; 
export const GET_SINGLE_USER_FAILED = 'GET_SINGLE_USER_FAILED';
export const DELETE_SINGLE_USER_START = 'DELETE_SINGLE_USER_START';
export const DELETE_SINGLE_USER_SUCCESS = 'DELETE_SINGLE_USER_SUCCESS';
export const DELETE_SINGLE_USER_FAILED = 'DELETE_SINGLE_USER_FAILED';
export const GET_USER_PHOTO_FAILED = 'GET_USER_PHOTO_FAILED';
export const GET_USER_PHOTO_SUCCESS = 'GET_USER_PHOTO_SUCCESS';

export const PERMISSION_START = 'PERMISSION_START'; 
export const PERMISSION_SUCCESS = 'PERMISSION_SUCCESS'; 
export const PERMISSION_FAILED = 'PERMISSION_FAILED'; 

export const ROLE_START = 'ADD_USER_ROLE_START';
export const ROLE_SUCCESS = 'ROLE_SUCCESS';
export const ROLE_FAILED = 'ROLE_FAILED';

export const ADD_NEW_USER_START = 'ADD_NEW_USER_START';
export const ADD_NEW_USER_SUCCESS = 'ADD_NEW_USER_SUCCESS';
export const ADD_NEW_USER_FAILED = 'ADD_NEW_USER_FAILED';

export const USER_CLEAR = 'USER_CLEAR';
export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const CATEGORY_START = 'CATEGORY_START';
export const CATEGORY_SUCCESS = 'CATEGORY_SUCCESS';
export const CATEGORY_FAILED = 'CATEGORY_FAILED';
export const CLEAR_CATEGORY_STATE = 'CLEAR_CATEGORY_STATE';

export const CATEGORY_ICON_START = 'CATEGORY_ICON_START';
export const CLEAR_CATEGORY_ICON_STATE = 'CLEAR_CATEGORY_ICON_STATE';
export const CATEGORY_ICON_SUCCESS = 'CATEGORY_ICON_SUCCESS';
export const CATEGORY_ICON_FAILED = 'CATEGORY_ICON_FAILED';

export const BRAND_START = 'BRAND_START';
export const CLEAR_BRAND_STATE = 'CLEAR_BRAND_STATE';
export const BRAND_SUCCESS = 'BRAND_SUCCESS';
export const BRAND_FAILED = 'BRAND_FAILED';

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';